### 114.115.160.119
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "libw",
  "password": "libw",
  "fullname": "libowen",
  "email": "27091925@qq.com",
  "organization": "Fudan University",
  "authorities": [
    "Contributor"
  ]
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "libw",
  "password": "libw"
}

###
GET http://localhost:8080/welcome
Accept: application/json

###
